### PR TITLE
Replace travis with GitHub actions

### PR DESCRIPTION
**Pull request by boris-petrov**
cc @Serabe

The tests pass on the latest stable JRuby as well as on the new one (which sets Ruby's version to 3.1.x).

Do you mind releasing a new version of the gem with these changes?

### CODE REVIEW

**Comment by boris-petrov** [comment]
Ping @Serabe :)

**Comment by boris-petrov** [comment]
@Serabe thanks for merging that! Do you mind releasing it in a new version? I think it should be a major one - 0.5.0 - because it has a breaking change - drops support of Ruby < 2.6.

**Comment by Serabe** [comment]
I'm trying, but I cannot get it working. Haven't used Ruby nor Java in a while and bundle is now refusing to install:

```sh
✘1 ➜ bundle                          
Fetching gem metadata from http://rubygems.org/.......
Could not find gem 'rmagick4j' in source at `.`.
The source contains 'rmagick4j' at: 0.5.0 java
```

**Comment by boris-petrov** [comment]
Yeah, I also spent a horrible amount of time trying to get this working (and the GitHub Actions build). Let me try to figure it out. What OS are you using?

**Comment by Serabe** [comment]
macOS

**Comment by boris-petrov** [comment]
I also get the same error when using the "global" `bundle` from Ruby 3.0.0. Using `jruby` works however - `jruby -S bundle`. No idea why. Perhaps try building by using `jruby -S`?

**Comment by boris-petrov** [comment]
Also, be sure to do that with JDK 8. Using 18, for example, doesn't work.

**Comment by boris-petrov** [comment]
On my side `jruby -S bundle`, `jruby -S rake clean` and then `jruby -S rake gem` seem to work. Again, using JDK 8 and JRuby 9.3.4.0. I'm on Linux but hopefully it's the same on Mac.

**Comment by boris-petrov** [comment]
@Serabe any luck with the `jruby` commands? :)

**Comment by Serabe** [comment]
Not much, now it does not compile in my machine

```
BUILD FAILED
/Users/serabe/programming/play/RMagick4J/Magick4J/nbproject/build-impl.xml:438: The following error occurred while executing this line:
/Users/serabe/programming/play/RMagick4J/Magick4J/nbproject/build-impl.xml:224: Compile failed; see the compiler error output for details.
```

And cannot see the compiler output 🤦

**Comment by boris-petrov** [comment]
Yeah, I also struggled with this. :( And I couldn't figure out how to actually show it. But I guessed that the issue was my Java version and indeed it was. Did you try with JDK 8?

**Comment by boris-petrov** [comment]
@Serabe so, to get the compiler output, change the `ant -f #{BUILD_FILE} jar` line in `Rakefile` to `ant -f #{BUILD_FILE} jar > foo.log` - you'll see the compiler output in `foo.log`. At the bottom there should be the error.

**Comment by boris-petrov** [comment]
@Serabe sorry to ping you so much but I really would like to try this new version. :smile: Any way I can help?

**Comment by Serabe** [comment]
My time is really limited for a couple of weeks. Until I can get a build passing or add you to Rubygems (which has been failing for a while) is going to be complicated.

Sergio Arbeo

**Pull request merged**
