### PR TITLE
Try running the tests on travis-ci.

### PR DESCRIPTION
**Pull request by donv**
Hi @Serabe !

Could you enable build on travis-ci ?  Would be great to run some tests to make development easier.

### CODE REVIEW

**Comment by donv** [comment]
Oh.  Already enabled and running.  My bad.

**Comment by donv** [comment]
The test target on master doesn't actually run any tests.  The travis branch fails now.  I'll fix it, I am out of time for today.  Feel free to fix if you have the time.

Tests are green for me locally, so I think it is an environment problem.

**Comment by donv** [comment]
Hi @Serabe !

Tests are green in travis.  Ok to merge?

**Comment by Serabe** [comment]
Merged. @donv, feel free to merge this yourself! Thank you and tell me if you need more permissions.

**Comment by donv** [comment]
I can do the merges myself.  It's just nice to have a quick review and a 👍 by another developer with a fresh pair of eyes 😄 .

**Pull request merged**
